"""Additional authorized display refresh; leaves the completed experiment untouched."""
import argparse
import importlib
import shutil
import sys
import time
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
from s02_visualization import ROOT,OUT,PROJECT_ROOT,read,save,sha,plot_run

def core_figures():
    from v6_mujoco.system_capture.estimation import plot_style
    plot_style.FIG=OUT/'core_figures';plot_style.FIG.mkdir(parents=True,exist_ok=True)
    for name in ('fig1_errors','fig2_budget','fig3_contact','fig4_outcomes'):
        importlib.import_module('v6_mujoco.system_capture.estimation.'+name).main()
        shutil.copyfile(PROJECT_ROOT/'v6_mujoco/system_capture/estimation'/(name+'.py'),plot_style.FIG/(name+'.py'))
    shutil.copyfile(ROOT/'figures/README.md',plot_style.FIG/'README.md')
    shutil.copyfile(ROOT/'figures/latex_includes.tex',plot_style.FIG/'latex_includes.tex')
    with (plot_style.FIG/'README.md').open('a',encoding='utf-8') as f:
        f.write('\nThis refreshed derivative was generated by `python tools/s02_refresh_media.py --plots`. Original S02 experiment figures and handoff are retained at commit 7198178ad798624f6ea163244e03641b78a56a3c.\n')

def main():
    p=argparse.ArgumentParser();p.add_argument('--plots',action='store_true');p.add_argument('--videos',action='store_true');args=p.parse_args()
    OUT.mkdir(parents=True,exist_ok=True)
    handoff=read(ROOT/'handoff.json')
    for rel,digest in handoff['evidence_sha256'].items():
        assert sha(PROJECT_ROOT/rel)==digest, 'Changed experiment evidence: '+rel
    names=[x['name'] for x in read(ROOT/'run_ledger.json')['attempts']]
    start=time.perf_counter();cpu=time.process_time()
    if args.plots:
        for name in names:plot_run(name)
        core_figures()
    if args.videos:
        from s02_render import run
        for name in ['E0_C2']+[x for x in names if x!='E0_C2']:run(name)
    label='plots' if args.plots else 'videos'
    save(OUT/(label+'_execution.json'),{'original_experiment_commit':'7198178ad798624f6ea163244e03641b78a56a3c',
         'run_names':names,'physics_steps':0,'new_physical_attempts':0,'parent_cpu_s':time.process_time()-cpu,
         'wall_s':time.perf_counter()-start,'scope':'User-authorized post-completion visual refresh, separate from the completed S02 experiment budget.'})
    for rel,digest in handoff['evidence_sha256'].items():assert sha(PROJECT_ROOT/rel)==digest,rel

if __name__=='__main__':main()
